// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OreTracking.Api.Services;

#nullable disable

namespace OreTracking.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("TestApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("TestApi.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgettoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgettoId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("TestApi.Models.OraLavorata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ore")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgettoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgettoId");

                    b.ToTable("OreLavorate");
                });

            modelBuilder.Entity("TestApi.Models.Progetto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Progetti");
                });

            modelBuilder.Entity("TestApi.Models.Nota", b =>
                {
                    b.HasOne("TestApi.Models.Progetto", "Progetto")
                        .WithMany("Note")
                        .HasForeignKey("ProgettoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Progetto");
                });

            modelBuilder.Entity("TestApi.Models.OraLavorata", b =>
                {
                    b.HasOne("TestApi.Models.Progetto", "Progetto")
                        .WithMany("OreLavorate")
                        .HasForeignKey("ProgettoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Progetto");
                });

            modelBuilder.Entity("TestApi.Models.Progetto", b =>
                {
                    b.HasOne("TestApi.Models.Cliente", "Cliente")
                        .WithMany("Progetti")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TestApi.Models.Cliente", b =>
                {
                    b.Navigation("Progetti");
                });

            modelBuilder.Entity("TestApi.Models.Progetto", b =>
                {
                    b.Navigation("Note");

                    b.Navigation("OreLavorate");
                });
#pragma warning restore 612, 618
        }
    }
}
